name: solution_challenge_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

#-----packages-----#
dependencies:
  flutter:
    sdk: flutter

  # Utilities Packages
  flutter_native_splash: ^2.3.10
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  smooth_page_indicator: ^1.1.0
  change_app_package_name: ^1.1.0
  carousel_slider: ^4.2.1

  #authentication
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

  #google signin & api
  google_sign_in: ^6.2.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1

  #calendar
  syncfusion_flutter_calendar: ^24.2.5+1

  #music playing
  rxdart: ^0.27.7
  just_audio: ^0.9.36

  #chatgpt
  chat_gpt_sdk: ^3.0.1

  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # SVG images
  flutter_svg: ^2.0.9

  # State Management
  get: ^4.6.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - imageAssets/appbarBackground.gif
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/login_page/
    - assets/images/appbar/
    - assets/images/image_carousel/
    - assets/music/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
